# Generated by Django 6.1.1 on 2026-10-04 22:01

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('playbook_id', models.CharField(max_length=100)),
                ('current_order', models.PositiveIntegerField()),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField()),
                ('audience', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32))),
                ('expects', models.CharField(choices=[('confirm', 'Confirm'), ('choice', 'Choice'), ('text', 'Text'), ('none', 'None')], default='confirm', max_length=16)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('next_on', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='playbooks.playbook')),
            ],
            options={
                'ordering': ['playbook', 'order'],
                'constraints': [models.UniqueConstraint(fields=('playbook', 'order'), name='step_playbook_order')],
            },
        ),
    ]
