# Generated by Django 6.1.1 on 2026-10-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='feature_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
