# Generated by Django 6.1.1 on 2026-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0002_playbookrun_feature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='facts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='step',
            name='answer_from',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='step',
            name='lookup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
