# Generated by Django 6.1.1 on 2026-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0003_step_lookup_and_run_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
