# Generated by Django 6.1.1 on 2026-10-04 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('detail', models.JSONField(default=dict)),
            ],
        ),
    ]
