# Generated by Django 6.1.1 on 2026-10-04 22:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('source_path', models.CharField(max_length=500)),
                ('doc_type', models.CharField(max_length=64)),
                ('classification', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ['document', 'order'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_gin')],
                'constraints': [models.UniqueConstraint(fields=('document', 'order'), name='chunk_document_order')],
            },
        ),
    ]
