# Generated by Django 6.1.1 on 2026-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='staff_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
