# Generated by Django 6.1.1 on 2026-10-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
