# Generated by Django 6.1.1 on 2026-10-06 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_message_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('rating', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=8)),
                ('reason', models.CharField(blank=True, choices=[('wrong_answer', 'Wrong answer'), ('wrong_source', 'Wrong source'), ('wrong_feature', 'Wrong kind of help'), ('too_slow', 'Too slow'), ('other', 'Other')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversation.message')),
            ],
            options={
                'indexes': [models.Index(fields=['rating', 'updated_at'], name='conversatio_rating_bbaafb_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'staff_id'), name='feedback_once_per_staff')],
            },
        ),
    ]
