# Generated by Django 6.1.1 on 2026-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_feedback_and_message_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
