"""Interfaces for the bank's systems. The MCP tools depend on these, so a real client and
an in-memory fake can be swapped without changing the tools."""

from typing import Any, Protocol


class CoreBankingClient(Protocol):
    async def get_account(self, account_number: str) -> dict[str, Any]: ...
    async def list_transactions(
        self, account_number: str, **filters: Any
    ) -> list[dict[str, Any]]: ...
    async def get_transaction(self, reference: str) -> dict[str, Any]: ...
    async def get_customer(self, customer_number: str) -> dict[str, Any]: ...


class ServiceCatalogClient(Protocol):
    async def search_products(self, query: str) -> list[dict[str, Any]]: ...
    async def get_product(self, code: str) -> dict[str, Any]: ...
    async def get_requirements(self, request_type: str) -> dict[str, Any]: ...
    async def open_requests(self, customer_number: str) -> list[dict[str, Any]]: ...
