# Generated by Django 6.1.1 on 2026-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('succeeded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip', 'created_at'], name='identity_lo_ip_c0fda0_idx')],
            },
        ),
    ]
